name: Atualizar CSV do Google Drive

on:
  schedule:
    - cron: '0 */1 * * *'   # Executa a cada 1 hora
  workflow_dispatch:       # Permite execução manual

jobs:
  atualizar-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Baixar CSV do Google Drive
        run: |
          curl -L "https://drive.google.com/uc?export=download&id=17tW1PwgxUpR94Dtg4MHe0K7QqOv7VFHQ" -o FOR.BIZA.SGI.csv

      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Commit & push se houver alterações
        run: |
          git add FOR.BIZA.SGI.csv
          git diff --cached --quiet || git commit -m "Atualização automática do CSV via Google Drive" && git push
